// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TrafficMarkIpKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ipv4Addr  [4]uint8
}

// LoadTrafficMark returns the embedded CollectionSpec for TrafficMark.
func LoadTrafficMark() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrafficMarkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TrafficMark: %w", err)
	}

	return spec, err
}

// LoadTrafficMarkObjects loads TrafficMark and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TrafficMarkObjects
//	*TrafficMarkPrograms
//	*TrafficMarkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTrafficMarkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTrafficMark()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TrafficMarkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrafficMarkSpecs struct {
	TrafficMarkProgramSpecs
	TrafficMarkMapSpecs
	TrafficMarkVariableSpecs
}

// TrafficMarkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrafficMarkProgramSpecs struct {
	DoMarkEgress  *ebpf.ProgramSpec `ebpf:"do_mark_egress"`
	DoMarkIngress *ebpf.ProgramSpec `ebpf:"do_mark_ingress"`
}

// TrafficMarkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrafficMarkMapSpecs struct {
	IpMarks *ebpf.MapSpec `ebpf:"ip_marks"`
}

// TrafficMarkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrafficMarkVariableSpecs struct {
}

// TrafficMarkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTrafficMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrafficMarkObjects struct {
	TrafficMarkPrograms
	TrafficMarkMaps
	TrafficMarkVariables
}

func (o *TrafficMarkObjects) Close() error {
	return _TrafficMarkClose(
		&o.TrafficMarkPrograms,
		&o.TrafficMarkMaps,
	)
}

// TrafficMarkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTrafficMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrafficMarkMaps struct {
	IpMarks *ebpf.Map `ebpf:"ip_marks"`
}

func (m *TrafficMarkMaps) Close() error {
	return _TrafficMarkClose(
		m.IpMarks,
	)
}

// TrafficMarkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTrafficMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrafficMarkVariables struct {
}

// TrafficMarkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTrafficMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrafficMarkPrograms struct {
	DoMarkEgress  *ebpf.Program `ebpf:"do_mark_egress"`
	DoMarkIngress *ebpf.Program `ebpf:"do_mark_ingress"`
}

func (p *TrafficMarkPrograms) Close() error {
	return _TrafficMarkClose(
		p.DoMarkEgress,
		p.DoMarkIngress,
	)
}

func _TrafficMarkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trafficmark_arm64_bpfel.o
var _TrafficMarkBytes []byte
